apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubeapis.stable.example.com
spec:
  group: stable.example.com
  scope: Namespaced
  names:
    plural: kubeapis
    singular: kubeapi
    kind: KubeApi
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              required: ["hostUrl","serviceType"]
              type: object
              properties:
                replicas:
                  type: integer
                hostUrl:
                  type: string
                serviceType:
                  type: string
                container:
                  required: ["image", "containerPort"]
                  type: object
                  properties:
                    image:
                      type: string
                    containerPort:
                      type: integer

