apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go-rest-api-rs
  labels:
    app: go-rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-rest-api
  template:
    metadata:
      labels:
        app: go-rest-api
    spec:
      containers:
        - name: go-rest-api
          image: pkbhowmick/go-rest-api
          ports:
          - containerPort: 8080
