apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: abc
      image: busybox
      volumeMounts:
        - name: tem-vol
          mountPath: "/temp"
      command: ["sleep", "1000000"]
  volumes:
    - name: tem-vol
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: test-vol
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: standard
            resources:
              requests:
                storage: 1Gi
