apiVersion: v1
kind: Pod
metadata:
  name: mysql-test
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password

      volumeMounts:
        - name: site-data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: site-data
          mountPath: /var/www/html
          subPath: html
  volumes:
    - name: site-data
      persistentVolumeClaim:
        claimName: pvc-1
    - secret:
        secretName: mysql-secret
      name: mysql-secret







