apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod-2
spec:
  containers:
    - name: mongo
      image: mongo
      volumeMounts:
        - name: data
          mountPath: "/data"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-2

