apiVersion: v1
kind: Pod
metadata:
  name: mysql-test-subpath
spec:
  containers:
  - name: mysql
    image: mysql:8.0.21
    env:
     - name: MYSQL_ROOT_PASSWORD
       valueFrom:
         secretKeyRef:
           name: mysql-secret
           key: password
     - name: MYSQL_ROOT_USERNAME
       valueFrom:
         secretKeyRef:
           name: mysql-secret
           key: username

    volumeMounts:
    - name: site-data
      mountPath: /var/lib/mysql
  volumes:
  - name: site-data
    persistentVolumeClaim:
      claimName: pvc-1





